### ISSUE TITLE
Fix social account login in production server

### ISSUE THREAD

**Issue by dimasciput** [kartoza/freshwaterbiodiversity.org#281]
## Problem

Couldn't login with google or github in production server, http://freshwaterbiodiversity.org.

## Solution

@timlinux we need them to create oauth app in github and google, then we can put the secret key to the freshwater site. But for now I will create it with my account.

**Comment by dimasciput** [comment]
@Vries14 please test it in the production server, thanks.

**Comment by Vries14** [comment]
@dimasciput , When I try to log in with social account it takes me to a sign-up page saying that im about to log in with the social account. When I click on sign up it tells me that there are already users registered with those email address
![Screenshot_2018-10-31 Signup.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6952abafc89a0011b75b37/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6417773e7a55e3187982ed3daf0037431f1d11f6140b1b56f6eb8c7af7e23d718c0e0deb853e5a75c63d10febdd64cbb02bf32975dc7e7e2de139db17770a599855d3f190f198cfb5d3ca69048c958f042e35f18.png)

**Comment by dimasciput** [comment]
@Vries14 yes, please use other email address

**Comment by Vries14** [comment]
@dimasciput  I tried to log in with Github and I got an email:  _A third-party OAuth Application (Freshwaterbiodiversity) with public_repo, read:org, and user:email scopes was recently authorized to access your account.
Visit https://github.com/settings/connections/applications/576c290ee27700850f26 for more information._
But I still cant log in with Github account, It takes me back to the sign up page with my email address from Github account already inserted in column.

**Comment by dimasciput** [comment]
@Vries14 ok, try again. I removed all of your accounts from the site.

**Comment by Vries14** [comment]
That must have been the problem, Im now able to login with social accounts
