### ISSUE TITLE
Add contextual legends

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/freshwaterbiodiversity.org#286]
# Problem

Some of the legends we have for our layers are very long. Although we have a scrollbar to navigate the legend it will be nice to have contextual legends.

# Solution

Contextual legends are based on the bounding box of the layer visible
ie
http://maps.kartoza.com/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=kartoza:lada_land_use&styles=&bbox=1822825.125,-4147822.75,3667056.0,-2744173.5&srs=EPSG:3857

**Comment by gubuntu** [comment]
@NyakudyaA please rather put this and other general bims issues in django-bims. Only very instance-specific issues should go in healthyrivers or ledet.

**Comment by NyakudyaA** [comment]
This issue was moved to kartoza/django-bims#469
