### ISSUE TITLE
UI is not consistent

### ISSUE THREAD

**Issue by carina1000** [kartoza/freshwaterbiodiversity.org#288]

**Comment by carina1000** [comment]
# Problem

UI is not consistent, for example, there are at least 3 different cross/close symbols.

![Screen Shot 2018-10-31 at 14.57.23.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a379eb0c2e56415d4dbe5d4a1f06a3a3dc78e2a436628f0d0eeed43c5976ce3e40a5bad01fbf00e827821e81e4ef9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc58ff42e14a56a2143360f43b.png)
![Screen Shot 2018-10-31 at 14.57.30.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a379eb0c2e56415c4ebe5d4a1f06a3a3dc78e2a436628f0d0eeed43c5976ce3e40a5bad01fbf00e827821e81e4ef9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc58ff42e14a56a214366af43b.png)
![Screen Shot 2018-10-31 at 14.57.40.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a379eb0c2e56415b4ebe5d4a1f06a3a3dc78e2a436628f0d0eeed43c5976ce3e40a5bad01fbf00e827821e81e4ef9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc58ff42e14a56a2143f64f43b.png)

# Solution

Please see Icons here to use https://drive.google.com/drive/u/3/folders/1fgljBJo-w47N-dnXZqqsIrcKcjVgKwoy

Let me know if you need more icons!

**Comment by gubuntu** [comment]
move to django-bims pls

**Comment by NyakudyaA** [comment]
@carina1000 For migrating issues between repos please use https://github-issue-mover.appspot.com.

**Comment by carina1000** [comment]
Thanks @NyakudyaA I didn't even know that was possible! I have already made a new issue in the repo though
